const state={board:initialBoard(),turn:WHITE,selected:null,history:[],flipped:false,mode:'bot'};
const boardEl=document.getElementById('board'), statusEl=document.getElementById('status'), analysisEl=document.getElementById('analysis');
function render(){boardEl.innerHTML=''; const rows=[...Array(8).keys()], cols=[...Array(8).keys()]; if(state.flipped){rows.reverse();cols.reverse()} const moves=state.selected?legalMoves(state.board,state.turn).filter(m=>m.from[0]===state.selected[0]&&m.from[1]===state.selected[1]):[]; for(const r of rows)for(const c of cols){const cell=document.createElement('button'); cell.className=`cell ${(r+c)%2?'dark':'light'}`; cell.dataset.r=r;cell.dataset.c=c; const move=moves.find(m=>m.to[0]===r&&m.to[1]===c); if(move)cell.classList.add('target'); if(state.selected?.[0]===r&&state.selected?.[1]===c)cell.classList.add('selected'); const p=state.board[r][c]; if(p){const piece=document.createElement('span'); piece.className=`piece ${p.color===WHITE?'white':'black'} ${p.king?'king':''}`; piece.textContent=p.king?'♛':''; cell.append(piece)} cell.onclick=()=>clickCell(r,c); boardEl.append(cell)} statusEl.textContent=`Ход: ${state.turn===WHITE?'белые (вы)':'черные (бот)'}. Обязательные взятия учитываются.`}
function clickCell(r,c){if(state.turn!==WHITE)return; const p=state.board[r][c]; if(p?.color===WHITE){state.selected=[r,c];render();return} if(!state.selected)return; const m=legalMoves(state.board,WHITE).find(x=>x.from[0]===state.selected[0]&&x.from[1]===state.selected[1]&&x.to[0]===r&&x.to[1]===c); if(m)move(m,true); else state.selected=null; render()}
function move(m,botAfter){state.history.push({board:cloneBoard(state.board),turn:state.turn}); state.board=applyMove(state.board,m); state.turn=state.turn===WHITE?BLACK:WHITE; state.selected=null; explain(m); render(); if(botAfter&&state.turn===BLACK)setTimeout(botMove,350)}
function botMove(){const best=bestMoves(state.board,BLACK,5)[0]; if(best)move(best,false)}
function explain(last){const side=state.turn===WHITE?WHITE:BLACK, candidates=bestMoves(state.board,side,4); const evalForWhite=evaluate(state.board,WHITE); analysisEl.innerHTML=`<p>📍 <b>Оценка позиции:</b> ${evalForWhite>0?'+':''}${evalForWhite} для белых</p><p>🏆 <b>Последний ход:</b> ${notation(last)}</p><p>📖 <b>Почему:</b> ход ${last.captures.length?'забирает материал и сохраняет темп':'улучшает активность и контроль центра'}.</p><p>⚠️ <b>После ответа:</b> проверяем обязательные взятия, угрозы прохода в дамки и тактические удары.</p><p>🎯 <b>План:</b> занять центр, навязать выгодный размен, провести отдалённую шашку в дамки и не давать контригры.</p><p>♟ <b>Лучшие альтернативы:</b></p><ol>${candidates.map(m=>`<li>${notation(m)} — оценка ${m.score>0?'+':''}${m.score}</li>`).join('')||'<li>Нет легальных ходов</li>'}</ol>`}
document.getElementById('hint').onclick=()=>{const ms=bestMoves(state.board,state.turn,5); analysisEl.innerHTML=`<p>📍 <b>Оценка:</b> ${evaluate(state.board,WHITE)}</p><p>🏆 <b>Лучший ход:</b> ${ms[0]?notation(ms[0]):'нет ходов'}</p><p>📖 <b>Почему:</b> выбран поиском alpha-beta с учетом материала, дамок, центра и темпа.</p><p>♟ <b>Топ-3:</b></p><ol>${ms.map(m=>`<li>${notation(m)} — ${m.score}</li>`).join('')}</ol>`};
document.getElementById('undo').onclick=()=>{const h=state.history.pop(); if(h){state.board=h.board;state.turn=h.turn;render()}};document.getElementById('flip').onclick=()=>{state.flipped=!state.flipped;render()};document.getElementById('newBot').onclick=()=>{state.board=initialBoard();state.turn=WHITE;state.history=[];analysisEl.textContent='Новая партия против бота готова.';render()};document.getElementById('copyRoom').onclick=()=>{const id=Math.random().toString(36).slice(2,8).toUpperCase(); const url=location.href.split('#')[0]+'#room-'+id; document.getElementById('room').textContent=`Комната ${id}: ${url}. В следующей версии подключим WebRTC/сервер матчмейкинга; сейчас это UX-прототип ссылки.`; navigator.clipboard?.writeText(url)};render();
