const SIZE=8, WHITE='w', BLACK='b';
const dirs=[[1,1],[1,-1],[-1,1],[-1,-1]];
function initialBoard(){const b=Array.from({length:SIZE},()=>Array(SIZE).fill(null));for(let r=0;r<3;r++)for(let c=0;c<SIZE;c++)if((r+c)%2)b[r][c]={color:BLACK,king:false};for(let r=5;r<8;r++)for(let c=0;c<SIZE;c++)if((r+c)%2)b[r][c]={color:WHITE,king:false};return b}
function cloneBoard(b){return b.map(row=>row.map(p=>p&&{...p}))}function inside(r,c){return r>=0&&r<SIZE&&c>=0&&c<SIZE}function enemy(a,b){return a&&b&&a.color!==b.color}function sq(r,c){return String.fromCharCode(97+c)+(8-r)}
function simpleMoves(b,r,c){const p=b[r][c], out=[]; if(!p)return out; const steps=p.king?dirs:(p.color===WHITE?[[-1,1],[-1,-1]]:[[1,1],[1,-1]]); for(const[dR,dC]of steps){let nr=r+dR,nc=c+dC;while(inside(nr,nc)&&!b[nr][nc]){out.push({from:[r,c],to:[nr,nc],captures:[]}); if(!p.king)break; nr+=dR;nc+=dC}}return out}
function capturesFrom(b,r,c,path=[],seen=new Set(),origin=[r,c]){const p=b[r][c], out=[]; if(!p)return out; for(const[dR,dC]of dirs){let mr=r+dR,mc=c+dC; while(inside(mr,mc)&&!b[mr][mc]&&p.king){mr+=dR;mc+=dC} if(!inside(mr,mc)||!enemy(p,b[mr][mc])||seen.has(mr+','+mc))continue; let lr=mr+dR,lc=mc+dC; while(inside(lr,lc)&&!b[lr][lc]){const nb=cloneBoard(b); nb[r][c]=null; nb[mr][mc]=null; nb[lr][lc]=p; const cap=[...path,[mr,mc]]; const next=capturesFrom(nb,lr,lc,cap,new Set([...seen,mr+','+mc]),origin); if(next.length)out.push(...next); else out.push({from:origin,to:[lr,lc],captures:cap}); if(!p.king)break; lr+=dR;lc+=dC}} return out}
function legalMoves(b,color){let caps=[], moves=[]; for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(b[r][c]?.color===color){const cs=capturesFrom(b,r,c); caps.push(...cs); moves.push(...simpleMoves(b,r,c))} return caps.length?caps:moves}
function applyMove(b,m){const nb=cloneBoard(b), p=nb[m.from[0]][m.from[1]]; nb[m.from[0]][m.from[1]]=null; for(const [r,c] of m.captures)nb[r][c]=null; if((p.color===WHITE&&m.to[0]===0)||(p.color===BLACK&&m.to[0]===7))p.king=true; nb[m.to[0]][m.to[1]]=p; return nb}
function evaluate(b,color){let score=0; for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const p=b[r][c]; if(!p)continue; const advance=p.color===WHITE?7-r:r; let v=(p.king?5:1)+advance*.08+((c>1&&c<6&&r>1&&r<6)?.12:0); score+=p.color===color?v:-v} return Number(score.toFixed(2))}
function bestMoves(b,color,depth=4){function search(board,side,d,a=-1e9,beta=1e9){const ms=legalMoves(board,side); if(!d||!ms.length)return evaluate(board,color); let best=side===color?-1e9:1e9; for(const m of ms){const val=search(applyMove(board,m),side===WHITE?BLACK:WHITE,d-1,a,beta); if(side===color){best=Math.max(best,val);a=Math.max(a,val)}else{best=Math.min(best,val);beta=Math.min(beta,val)} if(beta<=a)break}return best}return legalMoves(b,color).map(m=>({...m,score:search(applyMove(b,m),color===WHITE?BLACK:WHITE,depth-1)})).sort((a,b)=>b.score-a.score).slice(0,3)}
function notation(m){return `${sq(...m.from)}${m.captures.length?'x':'-'}${sq(...m.to)}`}
if(typeof module!=='undefined')module.exports={initialBoard,legalMoves,applyMove,evaluate,bestMoves,notation,WHITE,BLACK};
